name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: tests
        run: |
          output=$(pytest 2>&1)
          echo "$output"
          echo "pytest_output=$(echo "$output" | base64)" >> $GITHUB_ENV

      - name: Send notification to discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Lord Puller of Requests"
          message: "Pytest results:\n```\n$(echo '${{ env.pytest_output }}' | base64 --decode)\n```"
